# TaskFlow developer commands.
# Run `make help` to list targets.

.DEFAULT_GOAL := help
SHELL := /bin/bash

# Use the backend venv python if it exists, else system python.
PY := $(shell [ -x backend/.venv/bin/python ] && echo backend/.venv/bin/python || ([ -x backend/.venv/Scripts/python.exe ] && echo backend/.venv/Scripts/python.exe || echo python))

## --- Setup ---
.PHONY: install install-backend install-frontend
install: install-backend install-frontend ## Install all dependencies

install-backend: ## Create backend venv and install dev deps
	cd backend && python -m venv .venv && \
		.venv/bin/pip install -r requirements-dev.txt 2>/dev/null || \
		backend/.venv/Scripts/pip.exe install -r backend/requirements-dev.txt

install-frontend: ## Install frontend deps
	cd frontend && npm install

## --- Run ---
.PHONY: dev-backend dev-frontend up down logs
dev-backend: ## Run the backend dev server (SQLite)
	cd backend && .venv/bin/uvicorn app.main:app --reload --port 8000 2>/dev/null || \
		backend/.venv/Scripts/uvicorn.exe app.main:app --reload --port 8000

dev-frontend: ## Run the frontend dev server
	cd frontend && npm run dev

up: ## Start the full stack with Docker Compose
	docker compose up --build

down: ## Stop the Docker Compose stack
	docker compose down

logs: ## Tail Docker Compose logs
	docker compose logs -f

## --- Database ---
.PHONY: migrate migration
migrate: ## Apply database migrations
	cd backend && .venv/bin/alembic upgrade head 2>/dev/null || \
		backend/.venv/Scripts/alembic.exe upgrade head

migration: ## Create a new autogenerated migration (use: make migration m="message")
	cd backend && .venv/bin/alembic revision --autogenerate -m "$(m)" 2>/dev/null || \
		backend/.venv/Scripts/alembic.exe revision --autogenerate -m "$(m)"

## --- Quality ---
.PHONY: test test-backend test-frontend lint format
test: test-backend test-frontend ## Run all tests

test-backend: ## Run backend tests with coverage
	cd backend && .venv/bin/pytest --cov=app 2>/dev/null || \
		backend/.venv/Scripts/pytest.exe --cov=app

test-frontend: ## Run frontend tests
	cd frontend && npm run test

lint: ## Lint backend (ruff) and frontend (eslint)
	cd backend && .venv/bin/ruff check app tests 2>/dev/null || backend/.venv/Scripts/ruff.exe check app tests
	cd frontend && npm run lint

format: ## Format backend (ruff) and frontend (prettier)
	cd backend && .venv/bin/ruff format app tests 2>/dev/null || backend/.venv/Scripts/ruff.exe format app tests
	cd frontend && npm run format

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'
